---
    kind: Deployment
    apiVersion: apps/v1
    metadata:
      namespace: default
      name: api
      labels:
        app: api
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: api
      template:
        metadata:
          labels:
            app: api
        spec:
          containers:
            - name: api
              image: containous/whoami
              ports:
                - name: web
                  containerPort: 80
    
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: whoami
    
    spec:
      ports:
        - protocol: TCP
          name: web
          port: 80
      selector:
        app: whoami
    
    ---
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: whoami
      annotations:
        traefik.ingress.kubernetes.io/rule-type: PathPrefixStrip
    spec:
      rules:
      - host: ELB-ENDPOINT
        http:
          paths:
          - path: /whoami
            backend:
              serviceName: whoami
              servicePort: web